# Generated by Django 3.2.6 on 2022-06-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cropDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('alternateName', models.TextField(verbose_name='alternateName')),
                ('sowInstructions', models.TextField(verbose_name='spaceInstructions')),
                ('harvestInstructions', models.TextField(verbose_name='harvestInstructions')),
                ('compatiblePlants', models.TextField(verbose_name='compatiblePlants')),
                ('avoidInstructions', models.TextField(verbose_name='avoidInstructions')),
                ('culinaryHints', models.TextField(verbose_name='culinaryHints')),
                ('url', models.URLField(verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='dpDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpimg', models.ImageField(upload_to='', verbose_name='dpimg')),
            ],
        ),
    ]
