# Generated by Django 3.2.6 on 2022-06-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_auto_20220605_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='cropDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('alternateName', models.TextField(verbose_name='alternateName')),
                ('sowInstructions', models.TextField(verbose_name='sowInstructions')),
                ('spaceInstructions', models.TextField(verbose_name='spaceInstructions')),
                ('harvestInstructions', models.TextField(verbose_name='harvestInstructions')),
                ('compatiblePlants', models.TextField(verbose_name='compatiblePlants')),
                ('avoidInstructions', models.TextField(verbose_name='avoidInstructions')),
                ('culinaryHints', models.TextField(verbose_name='culinaryHints')),
                ('culinaryPreservation', models.TextField(verbose_name='culinaryPreservation')),
                ('url', models.URLField(verbose_name='url')),
            ],
        ),
        migrations.DeleteModel(
            name='cropInfo',
        ),
    ]
