# Generated by Django 4.0.4 on 2022-06-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_auto_20220605_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpdet',
            name='dpimg',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
