# Generated by Django 4.0.4 on 2022-06-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_alter_dpdet_dpimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='dpDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('dpimg', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='dpDet',
        ),
    ]
