# Generated by Django 4.0.4 on 2022-06-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0005_dpdetails_delete_dpdet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpdetails',
            name='dpimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
