# Generated by Django 4.0.5 on 2022-06-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_alter_dpdetails_dpimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='diseaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseaseName', models.TextField(verbose_name='diseaseName')),
                ('context', models.TextField(verbose_name='context')),
            ],
        ),
        migrations.AlterField(
            model_name='dpdetails',
            name='dpimg',
            field=models.ImageField(blank=True, null=True, upload_to='data/'),
        ),
    ]
